// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahcdKVKfLHtr-GFvM84b8BjnMOdLcb6M',
    appId: '1:347003680626:web:6c6ee32281e74545ddcfeb',
    messagingSenderId: '347003680626',
    projectId: 'wms-workshop',
    authDomain: 'wms-workshop.firebaseapp.com',
    storageBucket: 'wms-workshop.firebasestorage.app',
    measurementId: 'G-QHTMN6MFC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvgpYj1h1RWtlw2LtGFq9iu9EVMIgvKk',
    appId: '1:347003680626:android:301a797350156d9eddcfeb',
    messagingSenderId: '347003680626',
    projectId: 'wms-workshop',
    storageBucket: 'wms-workshop.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsh68uFjKlKqPiThKt1jaj7QSoQxcxuEE',
    appId: '1:347003680626:ios:6a9b83904a30ecb4ddcfeb',
    messagingSenderId: '347003680626',
    projectId: 'wms-workshop',
    storageBucket: 'wms-workshop.firebasestorage.app',
    iosBundleId: 'com.example.wmsMobileApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsh68uFjKlKqPiThKt1jaj7QSoQxcxuEE',
    appId: '1:347003680626:ios:6a9b83904a30ecb4ddcfeb',
    messagingSenderId: '347003680626',
    projectId: 'wms-workshop',
    storageBucket: 'wms-workshop.firebasestorage.app',
    iosBundleId: 'com.example.wmsMobileApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBahcdKVKfLHtr-GFvM84b8BjnMOdLcb6M',
    appId: '1:347003680626:web:6c6ee32281e74545ddcfeb',
    messagingSenderId: '347003680626',
    projectId: 'wms-workshop',
    authDomain: 'wms-workshop.firebaseapp.com',
    storageBucket: 'wms-workshop.firebasestorage.app',
    measurementId: 'G-QHTMN6MFC1',
  );

}